dependencies {
    modImplementation(project(":modules:CTNH-Lib")){transitive = false}

    modImplementation(ctnh.emi){
        accessTransformers.configure(it) {
            config = project.file('src/main/resources/META-INF/accesstransformer.cfg')
        }
    }
}

//jar {
//    manifest {
//        attributes([
//                'MixinConnector': 'com.ctnh.cei.MixinConnector'
//        ])
//    }
//}