org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

minecraft_version = 1.20.1
forge_version = 47.4.1
mapping_channel = parchment
mapping_version = 2023.09.03

# Mod Properties
mod_version = 0.0.1
maven_group = com.moguang.cei
archives_base_name = Create-Enough-Items
mod_id = cei
mod_name = Create Enough Items
mod_url = https://github.com/CTNH-Team/Create-Enough-Items
mod_author = CTNH Team
mod_description = Mod of the items & EMI part for the modpack Create: New Horizon.
mod_license = LGPLv3
